#!/usr/bin/env bash
# batch-propagate.sh — Weight engine driver for N zip codes.
#
# Usage:
#   bash canvas/scripts/batch-propagate.sh <design-element> <N> [zip-list]
#   bash canvas/scripts/batch-propagate.sh --skip-build <design-element> <N> [zip-list]
#
# Arguments:
#   design-element  Name of the design element (e.g. "BlockHeader")
#   N               Number of zip codes to process (positive integer)
#   zip-list        Optional comma-separated 4-digit numeric zips (e.g. "2113,2123,2133")
#                   Can also be set via ZIP_LIST env var.
#
# Default zip list (Deck 07 — Order=2, Axis=1, Types 1-5, Color=3):
#   2113, 2123, 2133, 2143, 2153
#
# All output files are written to canvas/components/ only.
# Never writes to production directories.

set -euo pipefail

# ─── Skip-build flag ──────────────────────────────────────────────────────────

SKIP_BUILD=false
if [[ "${1:-}" == "--skip-build" ]]; then
  SKIP_BUILD=true
  shift
fi

# ─── Validate arguments ───────────────────────────────────────────────────────

if [[ $# -lt 2 ]]; then
  echo "ERROR: Missing required arguments." >&2
  echo "Usage: bash canvas/scripts/batch-propagate.sh [--skip-build] <design-element> <N> [zip-list]" >&2
  exit 1
fi

ELEMENT="$1"
N="$2"
ZIP_LIST_ARG="${3:-}"

# Validate N is a positive integer
if ! [[ "$N" =~ ^[0-9]+$ ]] || [[ "$N" -lt 1 ]]; then
  echo "ERROR: N must be a positive integer. Got: $N" >&2
  exit 1
fi

# ─── Build canvas TypeScript (unless skipped) ─────────────────────────────────

if [[ "$SKIP_BUILD" == false ]]; then
  echo "Building canvas TypeScript..."
  (cd canvas && npm run build 2>/dev/null) || {
    echo "ERROR: canvas build failed. Check TypeScript errors in canvas/src/." >&2
    exit 1
  }
  echo "Build complete."
fi

# ─── Resolve zip list ─────────────────────────────────────────────────────────

# Priority: arg 3 > ZIP_LIST env var > default Deck 07 list
if [[ -n "$ZIP_LIST_ARG" ]]; then
  RAW_ZIP_LIST="$ZIP_LIST_ARG"
elif [[ -n "${ZIP_LIST:-}" ]]; then
  RAW_ZIP_LIST="$ZIP_LIST"
else
  # Default: Deck 07 (Order=2, Axis=1, Types 1-5, Color=3)
  RAW_ZIP_LIST="2113,2123,2133,2143,2153"
fi

# Parse comma-separated list into array
IFS=',' read -ra ALL_ZIPS <<< "$RAW_ZIP_LIST"

# Trim to N entries
ZIPS=()
for i in "${!ALL_ZIPS[@]}"; do
  if [[ $i -ge $N ]]; then
    break
  fi
  ZIPS+=("${ALL_ZIPS[$i]}")
done

echo "Processing ${#ZIPS[@]} zip(s) for element: $ELEMENT"

# ─── Generate output files ────────────────────────────────────────────────────

WRITTEN=0
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

mkdir -p "$REPO_ROOT/canvas/components"

for ZIP in "${ZIPS[@]}"; do
  # Strip any whitespace
  ZIP="${ZIP// /}"

  echo "  Processing zip: $ZIP"

  # Get CSS vars JSON from weight driver
  CSS_VARS_JSON=$(node "$SCRIPT_DIR/run-weight.mjs" "$ZIP") || {
    echo "  WARNING: Weight driver failed for zip $ZIP — skipping." >&2
    continue
  }

  OUTPUT_FILE="$REPO_ROOT/canvas/components/${ELEMENT}-${ZIP}.html"

  # Write HTML file with CSS vars as style block
  cat > "$OUTPUT_FILE" << HTMLEOF
<!-- canvas/components/${ELEMENT}-${ZIP}.html -->
<!-- Generated by batch-propagate.sh -->
<!-- Element: ${ELEMENT} | Zip: ${ZIP} -->
<!-- Do not edit manually — regenerate with batch-propagate.sh -->

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${ELEMENT} — Zip ${ZIP}</title>
  <style>
    :root {
$(echo "$CSS_VARS_JSON" | node -e "
const chunks = [];
process.stdin.resume();
process.stdin.on('data', d => chunks.push(d));
process.stdin.on('end', () => {
  const obj = JSON.parse(chunks.join(''));
  for (const [k, v] of Object.entries(obj)) {
    process.stdout.write('      ' + k + ': ' + v + ';\n');
  }
});
")    }
  </style>
</head>
<body>
  <!-- ${ELEMENT} canvas component for zip ${ZIP} -->
  <!-- CSS custom properties are loaded from the weight engine above -->
  <div class="canvas-component" data-zip="${ZIP}" data-element="${ELEMENT}">
    <!-- Component content goes here -->
  </div>
</body>
</html>
HTMLEOF

  echo "  WROTE: canvas/components/${ELEMENT}-${ZIP}.html"
  WRITTEN=$((WRITTEN + 1))
done

# ─── Summary ──────────────────────────────────────────────────────────────────

echo ""
echo "batch-propagate complete: $WRITTEN/${#ZIPS[@]} files written to canvas/components/"
